### PR TITLE
Add user ID tracking

### PR DESCRIPTION
**Pull request by OliverJAsh**
As per https://trello.com/c/kO8rLR3R/963-use-imgix-tracking-parameter

### CODE REVIEW

**Review by lukechesser — APPROVED** [review]
Just to be clear, for legacy reasons, if given the decoded `ixid` param missing the final `userId` param, as in:

```
my-app;search;dog;5;

// instead of
my-app;search;dog;5;;
```

Will it properly handle that case and set the correct values, i.e. `userId = undefined`?

**Comment by lukechesser** [comment]
@OliverJAsh also, just noticed, can you update the README with the `userId`?

**Comment by OliverJAsh** [comment]
@lukechesser I added a test to check this. It does work without user ID.

**Review by samijaber — COMMENTED** [review]
👍

**Pull request merged**
